name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    env:
      CI: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --ignore-optional --non-interactive --silent
      - run: yarn test --bail --colors --ci

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          files: coverage/coverage-final.json
