name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    env:
      CI: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile --ignore-optional --non-interactive --silent
      - run: node --expose-gc node_modules/jest/bin/jest --forceExit --bail --colors --logHeapUsage --maxWorkers=2 --ci

      - name: Upload coverage to Codecov
        # https://github.com/codecov/codecov-bash/blob/1044b7a243e0ea0c05ed43c2acd8b7bb7cef340c/codecov#L158
        run: bash <(curl -s https://codecov.io/bash)
          -f ./coverage/coverage-final.json
          -F client
          -P ${{ github.event.number }}
          -B ${{ github.head_ref }}
          -C ${{ github.event.after }}
          -Z || echo 'Codecov upload failed'
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
